### ISSUE TITLE
message: 'duplicate key value violates unique constraint "refresh_tokens_user_id_key'

### ISSUE THREAD

**Issue by Libertad61** [pilcrowOnPaper/lucia-tutorial#1]
I must delete the refresh_token of this user in order to login again. I've got this err msg in the console:
{
  code: '23505',
  details: 'Key (user_id)=(ykiU4Fzk) already exists.',
  hint: null,
  message: 'duplicate key value violates unique constraint "refresh_tokens_user_id_key"'
} and this lucia err msg: LuciaError: REQUEST_UNAUTHORIZED
    at handleRefreshRequest

**Comment by pilcrowonpaper** [comment]
Can you tell me which version of lucia-sveltekit you're using?

**Comment by Libertad61** [comment]
"@lucia-sveltekit/adapter-supabase": "^0.2.9",
		"lucia-sveltekit": "^0.4.1"
	}

**Comment by pilcrowonpaper** [comment]
Yeah, sorry about that.

This example became outdated in 2 days. make sure lucia and the adapter matches the package.json version

**Comment by Libertad61** [comment]
okay Boss! :-)

**Comment by pilcrowonpaper** [comment]
I just updated the entire thing. Re-install lucia and the adapter again (v0.5.0 and v0.3.0). The biggest change is that `users` and `refresh_tokens` table are now renamed to `user` and `refresh_token`. 

Sorry for all the change, but this version will likely be pretty stable.

**Comment by Libertad61** [comment]
Okay, thank you for the update! By the way, I followed too the Supabase guide for sveltekit and it's implementing only local storage for the authentication, no cookies... What is the best way to do? cookies like u, local storage or combination of both ??? and why are you using the secret key bypassing the RLS...? Is it mandatory with Lucia?

**Comment by pilcrowonpaper** [comment]
We want to access user data in the server (load functions + endpoint) so it has to be saved in cookies. If you store it the recommended way (as http-only cookies), you don't need to save it in the client since you'll be able to read tokens and user data using $session. I think the only way to access your database in the server (with RLS enabled) is using the secret key, so yes, it's likely mandatory.

**Comment by Libertad61** [comment]
okay for the cookies purpose. About RLS, I followed the sb guide and I can access profiles table with RLS enabled with anon_public key only!

**Comment by pilcrowonpaper** [comment]
Lucia needs to read all your data. The secret key is the only thing that allows the holder to do that. Why not try using an anon key if you're curious?

**Comment by Libertad61** [comment]
yep I will continue experimentation witj Lucia repo. There is too a new auth helper for sveltekit: https://supabase.com/blog/2022/07/13/supabase-auth-helpers-with-sveltekit-support
I will try too! I gained weight eating all these cookies! :-)

**Comment by pilcrowonpaper** [comment]
Supabase auth helper might be better if you want something simple, but could be somewhat limited depending on your use case (and I'm not sure about the security). It's definitely something Supabase needed though

**Comment by Libertad61** [comment]
yes, Authentication/authorization is an ample topic very sensitive, I continue to work on this in order to get better understanding!
